-- Unified schema for all companies in one Supabase project.
-- Each company gets 4 prefixed tables: {Company}_NominalRoll, _Exceptions, _Duty, _Configuration.
-- Run scripts/sync-schema.ts to apply to the hercules project.
-- Safe to re-run (IF NOT EXISTS, ON CONFLICT DO NOTHING).

GRANT USAGE ON SCHEMA public TO anon, authenticated;

DO $$
DECLARE
  companies text[] := ARRAY['Archer','Braves','Cougar','Stallion','Hercules','Test'];
  c text;
BEGIN
  FOREACH c IN ARRAY companies LOOP

    EXECUTE format('
      CREATE TABLE IF NOT EXISTS public."%s_NominalRoll" (
        rank    text NOT NULL,
        name    text NOT NULL,
        platoon text NOT NULL CHECK (platoon = ANY (ARRAY[''HQ'',''1'',''2'',''3'',''4''])),
        PRIMARY KEY (name)
      )', c);

    EXECUTE format('
      CREATE TABLE IF NOT EXISTS public."%s_Exceptions" (
        id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name    text NOT NULL,
        scope   text NOT NULL CHECK (scope = ANY (ARRAY[''Att C'',''Status'',''Off/Leave'',''Guard Duty'',''Report Sick'',''MA'',''Others''])),
        reason  text NOT NULL,
        start   date NOT NULL,
        "end"   date NOT NULL
      )', c);

    EXECUTE format('
      CREATE TABLE IF NOT EXISTS public."%s_Duty" (
        duty_type text NOT NULL CHECK (duty_type = ANY (ARRAY[''CDO'',''CDS'',''COS'',''PDS1'',''PDS2'',''PDS3'',''PDS4''])),
        date      date NOT NULL,
        name      text NOT NULL,
        PRIMARY KEY (duty_type, date)
      )', c);

    EXECUTE format('
      CREATE TABLE IF NOT EXISTS public."%s_Configuration" (
        parade_type text NOT NULL CHECK (parade_type = ANY (ARRAY[''First Parade'',''Last Parade''])),
        time        time NOT NULL,
        PRIMARY KEY (parade_type)
      )', c);

    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public."%s_NominalRoll"   TO authenticated', c);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public."%s_Exceptions"    TO authenticated', c);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public."%s_Duty"          TO authenticated', c);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public."%s_Configuration" TO authenticated', c);

    EXECUTE format('ALTER TABLE public."%s_NominalRoll"   ENABLE ROW LEVEL SECURITY', c);
    EXECUTE format('ALTER TABLE public."%s_Exceptions"    ENABLE ROW LEVEL SECURITY', c);
    EXECUTE format('ALTER TABLE public."%s_Duty"          ENABLE ROW LEVEL SECURITY', c);
    EXECUTE format('ALTER TABLE public."%s_Configuration" ENABLE ROW LEVEL SECURITY', c);

    EXECUTE format('DROP POLICY IF EXISTS "authenticated can manage %s_NominalRoll"   ON public."%s_NominalRoll"',   c, c);
    EXECUTE format('DROP POLICY IF EXISTS "authenticated can manage %s_Exceptions"    ON public."%s_Exceptions"',    c, c);
    EXECUTE format('DROP POLICY IF EXISTS "authenticated can manage %s_Duty"          ON public."%s_Duty"',          c, c);
    EXECUTE format('DROP POLICY IF EXISTS "authenticated can manage %s_Configuration" ON public."%s_Configuration"', c, c);

    EXECUTE format(
      'CREATE POLICY "authenticated can manage %s_NominalRoll" ON public."%s_NominalRoll"
       FOR ALL TO authenticated
       USING (auth.email() = lower(''%s'') || ''@40sar.internal'')
       WITH CHECK (auth.email() = lower(''%s'') || ''@40sar.internal'')',
      c, c, c, c);

    EXECUTE format(
      'CREATE POLICY "authenticated can manage %s_Exceptions" ON public."%s_Exceptions"
       FOR ALL TO authenticated
       USING (auth.email() = lower(''%s'') || ''@40sar.internal'')
       WITH CHECK (auth.email() = lower(''%s'') || ''@40sar.internal'')',
      c, c, c, c);

    EXECUTE format(
      'CREATE POLICY "authenticated can manage %s_Duty" ON public."%s_Duty"
       FOR ALL TO authenticated
       USING (auth.email() = lower(''%s'') || ''@40sar.internal'')
       WITH CHECK (auth.email() = lower(''%s'') || ''@40sar.internal'')',
      c, c, c, c);

    EXECUTE format(
      'CREATE POLICY "authenticated can manage %s_Configuration" ON public."%s_Configuration"
       FOR ALL TO authenticated
       USING (auth.email() = lower(''%s'') || ''@40sar.internal'')
       WITH CHECK (auth.email() = lower(''%s'') || ''@40sar.internal'')',
      c, c, c, c);

    EXECUTE format('
      INSERT INTO public."%s_Configuration" (parade_type, time) VALUES
        (''First Parade'', ''09:30:00''),
        (''Last Parade'',  ''17:30:00'')
      ON CONFLICT (parade_type) DO NOTHING', c);

  END LOOP;
END;
$$;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
