-- Canonical schema for all company Supabase projects.
-- Run scripts/sync-schema.ts to apply this to every company project.
-- All fields NOT NULL unless explicitly noted. Safe to re-run (IF NOT EXISTS).

CREATE TABLE IF NOT EXISTS public."NominalRoll" (
  rank    text NOT NULL,
  name    text NOT NULL,
  platoon text NOT NULL CHECK (platoon = ANY (ARRAY['HQ','1','2','3','4'])),
  PRIMARY KEY (name)
);
COMMENT ON TABLE public."NominalRoll" IS 'Exhaustive List of All Personnel';

CREATE TABLE IF NOT EXISTS public."Exceptions" (
  id      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name    text NOT NULL,
  scope   text NOT NULL CHECK (scope = ANY (ARRAY['Att C','Status','Off/Leave','Guard Duty','Report Sick','MA','Others'])),
  reason  text NOT NULL,
  start   date NOT NULL,
  "end"   date NOT NULL
  -- For single-day scopes (Guard Duty, Report Sick, MA): set start = end
);

CREATE TABLE IF NOT EXISTS public."Duty" (
  duty_type text NOT NULL CHECK (duty_type = ANY (ARRAY['CDO','CDS','COS','PDS1','PDS2','PDS3','PDS4'])),
  date      date NOT NULL,
  name      text NOT NULL,
  PRIMARY KEY (duty_type, date)
);
COMMENT ON TABLE public."Duty" IS 'Duty Roster';

CREATE TABLE IF NOT EXISTS public."Configuration" (
  parade_type text NOT NULL CHECK (parade_type = ANY (ARRAY['First Parade','Last Parade'])),
  time        time NOT NULL,
  PRIMARY KEY (parade_type)
);
COMMENT ON TABLE public."Configuration" IS 'Parade State Configuration';

-- Grant PostgREST access: schema usage for both roles, table access only for authenticated
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."NominalRoll"   TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."Exceptions"    TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."Duty"          TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public."Configuration" TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public         TO authenticated;

-- Enable RLS on all tables
ALTER TABLE public."NominalRoll"   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Exceptions"    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Duty"          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Configuration" ENABLE ROW LEVEL SECURITY;

-- Drop existing policies (idempotent)
DROP POLICY IF EXISTS "anon can read NominalRoll"              ON public."NominalRoll";
DROP POLICY IF EXISTS "authenticated can manage NominalRoll"   ON public."NominalRoll";
DROP POLICY IF EXISTS "anon can read Exceptions"               ON public."Exceptions";
DROP POLICY IF EXISTS "authenticated can manage Exceptions"    ON public."Exceptions";
DROP POLICY IF EXISTS "anon can read Duty"                     ON public."Duty";
DROP POLICY IF EXISTS "authenticated can manage Duty"          ON public."Duty";
DROP POLICY IF EXISTS "anon can read Configuration"            ON public."Configuration";
DROP POLICY IF EXISTS "authenticated can manage Configuration" ON public."Configuration";

-- Only authenticated commanders have full access; anon is blocked entirely
CREATE POLICY "authenticated can manage NominalRoll"
  ON public."NominalRoll" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "authenticated can manage Exceptions"
  ON public."Exceptions" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "authenticated can manage Duty"
  ON public."Duty" FOR ALL TO authenticated USING (true) WITH CHECK (true);

CREATE POLICY "authenticated can manage Configuration"
  ON public."Configuration" FOR ALL TO authenticated USING (true) WITH CHECK (true);

-- Default parade times (safe to re-run; ON CONFLICT does nothing)
INSERT INTO public."Configuration" (parade_type, time) VALUES
  ('First Parade', '09:30:00'),
  ('Last Parade',  '17:30:00')
ON CONFLICT (parade_type) DO NOTHING;
